import 'styles/globals.scss';
import { ReactNode } from 'react';

import cx from 'classnames';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import styles from 'app/layout.module.scss';
import Providers from 'app/providers';
import ErrorBoundary from 'components/error-boundary/ErrorBoundary';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: ReactNode;
}): JSX.Element {
    return (
        <html lang="en">
            <body className={inter.className}>
                <ErrorBoundary>
                    <Providers>
                        <main className={cx(styles.main)}>{children}</main>
                    </Providers>

                    <div id="modal-root" />
                    <div id="drawer-root" />
                </ErrorBoundary>
            </body>
        </html>
    );
}
